baseurl = "http://localhost:1313/"
disableLanguages = []
googleAnalytics = ""
summarylength = "20"
theme = "vex-hugo"
title = "Aoraki | Forestry and Fabrication"
[Languages.en]
copyright = "© Aoraki"
languageCode = "ja"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 3
[[menu.footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "商品"
url = "products"
weight = 2
[params]
author = "Binagai"
contact_form_action = "#"
currency = "¥"
description = "This is meta description"
logo = "images/aoraki-logo.svg"
logo_width = "100px"
snipcart_api = "NTM1N2I3MzUtN2FlMi00ZjIzLThlMWYtZWNjY2ZhZTkzNDEwNjM3NTkwMDEwMzI2ODY3Njcy"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.js"
[params.preloader]
enable = true
preloader = ""
[params.subscription]
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[taxonomies]
category = ["trailer house", "薪", "木材"]
