---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: /data/homepage.yml
  label: Homepage
#   type: heading
#   label: Blog Post
# - type: directory
#   path: /content/blog
#   label: Post
#   create: documents
#   match: "**/*"
#   new_doc_ext: '20191203072044'
#   templates:
#   - post
- type: heading
  label: Products
- type: directory
  path: content/products
  label: Product
  create: documents
  match: "**/*"
  templates:
  - product
- type: heading
  label: Contact
- type: document
  path: content/contact/_index.md
  label: Contact
- type: heading
  label: All Pages
- type: directory
  path: /content
  label: All Page
  create: all
  match: "**/*"
  - type: heading
  label: Translations
- type: directory
  path: /i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: document
  path: config.toml
  label: Configuration
# - type: directory
#   path: content
#   label: Pages
#   create: all
#   match: "*"
upload_dir: /static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
