---
label: Product
hide_body: false
fields:
- name: product_type
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: false
    label: 商品名
  - name: image_gallery
    type: file
    config:
      maxSize: 64
    label: ギャラリー
  config:
    min: 
    max: 
    labelField: 
  label: 商品種類
