---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: 品名
- type: image_gallery
  name: images
  label: 画像
- type: text
  name: description
  label: 説明
- type: text
  name: price
  label: 値段
- name: categories
  type: text
  config:
    required: false
  label: カテゴリー
- type: text
  name: discount_price
  label: 割引値段
- type: tag_list
  name: colors
  label: 色
- type: tag_list
  name: sizes
  label: 量・サイズ
- name: tags
  type: tag_list
  default: []
  label: タグ
pages:
- content/products/gyptsy-trailer.md
- content/products/gyptsy-trailer.md
- content/products/なら.md
- content/products/なら.md
- content/products/なら薪.md
- content/products/なら薪.md
- content/products/桜薪.md
- content/products/桜薪.md
