---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: 品名
- type: image_gallery
  name: images
  label: 画像
- type: text
  name: description
  label: 説明
- type: text
  name: price
  label: 値段
- type: text
  name: discount_price
  label: 割引値段
- type: tag_list
  name: colors
  label: 色
- type: tag_list
  name: sizes
  label: 量・サイズ
- name: category
  type: tag_list
  default: []
  label: " カテゴリー"
pages:
- content/products/桜薪.md
